[SLURM]
nsegments = 1
walltime = None
ntasks = None
mempercpu = None
partition = None
mailtype = None
mailuser = None

[PMEMD]
nstime = None
ntwx = None
dt = 0.002
cut = 10
ntc = 2
ntt = 3
gamma_ln = 3.0
ntwr = 5000000
ntpr = 50000
tempi = 310.0
temp0 = 310.0
pres0 = 1.0
imin = 0
irest = 1
ntx = 1
ntp = 1
ntb = 2
ig = -1
iwrap = 1
taup = 2.0
ioutfm = 1
restraint = None
constraint = None

