[SLURM]
nsegments  : 1
walltime   : 00-24:00
ntasks     : 8
mempercpu  : 2048M
partition  : cpu2019
mailtype   : all
mailuser   : makay.murray@uleth.ca
 
[PMEMD]
nstime     : 1
ntwx       : 25000
dt         : 0.002
cut        : 10
ntc        : 2
ntt        : 3
gamma_ln   : 3.0
ntwr       : 500000
ntpr       : 50000
tempi      : 310.0
temp0      : 310.0
pres0      : 0
imin       : 1
irest      : 5
ntx        : 1
ntp        : 2
ntb        : 1
ig         : -1
iwrap      : 1
taup       : 2.0
ioutfm     : 1
restraint  : 
constraint : 

